import Head from "next/head";
import Navbar from "./navbar";
import Footer from "./footer";
import { useAuth } from "../config/auth";
import { HashLoader } from "react-spinners";

export default function Layout({ children }) {
  const { isLoading } = useAuth();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <div className="min-h-screen max-w-screen fixed inset-0 z-[2] flex justify-center items-center">
          <HashLoader
            color="rgb(225 29 72)"
            loading={isLoading}
            size={50}
            speedMultiplier={2}
          />
        </div>
      ) : (
        <div className="max-w-screen">
          <Navbar />
          {children}
          <Footer />
        </div>
      )}
    </>
  )
}
