import Head from "next/head";
import Navbar from "./navbar";
import Footer from "./footer";
import { useAuth } from "../contexts/auth";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Loader from "./loader";
import { useLoading } from "../contexts/loading";

export default function Layout({ children }) {
  const { isUserLoading } = useAuth();
  const { isPageLoading } = useLoading();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isUserLoading ? (
        <Loader isLoading={isUserLoading} />
      ) : (
        <div className="max-w-screen">
          {isPageLoading && (
            <Loader isLoading={isPageLoading} />
          )}
          <Navbar />
          {children}
          <Footer />
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </div>
      )}
    </>
  )
}
